update death messages
Persistent-Kingdoms/persistent-factions pull request #4
Opened 2019-10-16 17:26 UTC by Cahrs

2019-10-17 07:04 UTC, luk3yx requested changes
There are some formatting issues and missing code at the end of the file.

Is `news/init.lua` meant to be copied into the top-level directory as well?

2019-10-17 07:04 UTC, luk3yx commented on mods/news/init.lua
> +            news_msg = " BREAKING NEWS: Local man \"" .. player .. "\" " .. reason_msg .. " \"" .. killer .. "\"."
```suggestion
            news_msg = " BREAKING NEWS: Local player \"" .. player .. "\" " .. reason_msg .. " \"" .. killer .. "\"."
```

2019-10-17 07:04 UTC, luk3yx commented on mods/news/init.lua
> +                news_msg = string.sub(news, 1, #news_msg-1)
```suggestion
                news_msg = string.sub(news, 1, #news_msg - 1)
```

2019-10-17 07:04 UTC, luk3yx commented on mods/news/init.lua
> +            local news_msg = "BREAKING NEWS: salt levels rise on PK."
```suggestion
            local news_msg = "BREAKING NEWS: Salt levels rise on PK."
```

2019-10-17 07:04 UTC, luk3yx commented on mods/news/init.lua
> +news.register_deathmsg_tbl("nodes",
Did you forget to write more code or remove this?

2019-10-22 00:04 UTC, Cahrs commented
Closing (reforked to fix some screwups)

2019-10-22 00:04 UTC, closed without merging